// Master recipe library. Plans are generated from this list — each meal can
// recur in future rotations, weighted by rating and recency.

export const RECIPE_LIBRARY = [
  // ── American weeknights ────────────────────────────────────────────────
  {
    id: 'sheet-pan-chicken',
    title: 'Sheet-pan chicken thighs + roasted potatoes',
    type: 'weeknight',
    time: '25 min',
    tags: ['quick', 'leftovers'],
    cuisine: 'American',
    notes: 'Season with garlic, olive oil, paprika. Everything on one pan at 425°F. Make extra — quesadillas sorted for later in the week.',
    ingredients: ['Chicken thighs (2 lb)', 'Yukon gold potatoes', 'Garlic', 'Olive oil', 'Paprika', 'Salt & pepper'],
  },
  {
    id: 'smash-burgers',
    title: 'Smash burgers + oven fries',
    type: 'weeknight',
    time: '20 min',
    tags: ['quick'],
    cuisine: 'American',
    notes: '80/20 beef smashed thin in cast iron, American or cheddar melted on. Oven fries at 425°F.',
    ingredients: ['80/20 ground beef (1 lb)', 'Burger buns', 'American or cheddar cheese', 'Russet potatoes', 'Ketchup', 'Mustard', 'Lettuce, tomato, onion'],
  },
  {
    id: 'bbq-chicken-wraps',
    title: 'BBQ chicken wraps + chips',
    type: 'weeknight',
    time: '15 min',
    tags: ['quick', 'leftovers'],
    cuisine: 'American',
    notes: 'Rotisserie chicken + BBQ sauce, flour tortillas, coleslaw, cheddar. Five-minute assembly. Low-effort weeknight.',
    ingredients: ['Rotisserie chicken', 'BBQ sauce', 'Flour tortillas', 'Coleslaw mix', 'Cheddar cheese', 'Tortilla chips'],
  },
  {
    id: 'turkey-meatloaf',
    title: 'Turkey meatloaf + mashed potatoes',
    type: 'weeknight',
    time: '45 min',
    tags: ['leftovers'],
    cuisine: 'American',
    notes: 'Ground turkey, onion, breadcrumbs, ketchup glaze. Make a double batch — leftovers slice cold for sandwiches.',
    ingredients: ['Ground turkey (1.5 lb)', 'Yellow onion', 'Breadcrumbs', 'Egg', 'Ketchup', 'Worcestershire', 'Russet potatoes', 'Butter', 'Milk'],
  },
  {
    id: 'chicken-caesar-bowls',
    title: 'Grilled chicken Caesar bowls',
    type: 'weeknight',
    time: '20 min',
    tags: ['quick'],
    cuisine: 'American',
    notes: 'Grill chicken breast, slice over chopped romaine with Caesar, parmesan, croutons. Light but filling.',
    ingredients: ['Chicken breast (1.5 lb)', 'Romaine', 'Caesar dressing', 'Parmesan', 'Croutons', 'Lemon'],
  },
  {
    id: 'pulled-pork-sandwiches',
    title: 'Pulled pork sandwiches + slaw',
    type: 'weeknight',
    time: '20 min (with pre-cooked pork)',
    tags: ['quick', 'leftovers'],
    cuisine: 'American',
    notes: 'Use slow-cooked or store-bought pulled pork, warm with BBQ sauce, brioche buns, quick coleslaw on top.',
    ingredients: ['Pulled pork (2 lb)', 'BBQ sauce', 'Brioche buns', 'Coleslaw mix', 'Coleslaw dressing', 'Pickles'],
  },

  // ── Mexican ────────────────────────────────────────────────────────────
  {
    id: 'ground-beef-tacos',
    title: 'Ground beef tacos',
    type: 'weeknight',
    time: '20 min',
    tags: ['quick'],
    cuisine: 'Mexican',
    notes: 'Quick seasoned beef, warm tortillas, shredded cheese, pico, sour cream, avocado. Shannon mild, Jim adds heat to his bowl.',
    ingredients: ['Ground beef (1 lb)', 'Flour tortillas', 'Shredded Mexican cheese', 'Sour cream', 'Avocado', 'Roma tomatoes', 'Limes', 'Taco seasoning'],
  },
  {
    id: 'taco-bowls',
    title: 'Taco bowls (deconstructed)',
    type: 'weeknight',
    time: '20 min',
    tags: ['quick'],
    cuisine: 'Mexican',
    notes: 'Rice base, seasoned meat, black beans, corn, shredded cheese, sour cream. Easy to customize by bowl.',
    ingredients: ['Ground turkey or beef (1 lb)', 'Rice', 'Canned black beans', 'Corn', 'Shredded cheese', 'Sour cream', 'Taco seasoning', 'Lime'],
  },
  {
    id: 'chicken-quesadillas',
    title: 'Chicken quesadillas',
    type: 'weeknight',
    time: '15 min',
    tags: ['quick', 'leftovers'],
    cuisine: 'Mexican',
    notes: 'Use leftover chicken or rotisserie. Flour tortillas, shredded cheese, quick pan crisp. Store-bought salsa.',
    ingredients: ['Leftover chicken or rotisserie', 'Flour tortillas', 'Shredded cheese', 'Sour cream', 'Salsa'],
  },
  {
    id: 'steak-tacos',
    title: 'Steak tacos with chimichurri',
    type: 'weeknight',
    time: '20 min',
    tags: ['quick', 'grill'],
    cuisine: 'Mexican',
    notes: 'Skirt or flank steak, quick high-heat sear, slice thin. Chimichurri is bright not heavy. Not spicy by default.',
    ingredients: ['Skirt or flank steak (1.5 lb)', 'Corn tortillas', 'Fresh parsley', 'Garlic', 'Red wine vinegar', 'Olive oil', 'White onion', 'Cilantro'],
  },
  {
    id: 'enchiladas-rojas',
    title: 'Chicken enchiladas rojas',
    type: 'weeknight',
    time: '40 min',
    tags: ['leftovers'],
    cuisine: 'Mexican',
    notes: 'Shredded chicken, corn tortillas dipped in red sauce, rolled and topped with cheese. Bake at 375°F until bubbly.',
    ingredients: ['Cooked shredded chicken (1 lb)', 'Corn tortillas', 'Red enchilada sauce', 'Monterey Jack cheese', 'White onion', 'Cilantro', 'Sour cream'],
  },
  {
    id: 'shrimp-fajitas',
    title: 'Shrimp fajitas',
    type: 'weeknight',
    time: '20 min',
    tags: ['quick'],
    cuisine: 'Mexican',
    notes: 'Shrimp + bell peppers + onions in a screaming-hot skillet, fajita seasoning, finish with lime. Warm tortillas.',
    ingredients: ['Shrimp (1 lb peeled)', 'Bell peppers (mixed)', 'Yellow onion', 'Fajita seasoning', 'Flour tortillas', 'Lime', 'Sour cream', 'Salsa'],
  },

  // ── Italian ────────────────────────────────────────────────────────────
  {
    id: 'pasta-meat-sauce',
    title: 'Pasta with quick meat sauce',
    type: 'weeknight',
    time: '25 min',
    tags: ['quick', 'leftovers'],
    cuisine: 'Italian',
    notes: 'Ground beef or turkey, crushed tomatoes elevated with garlic, oregano, splash of red wine. Parmesan at the table. Make a big batch.',
    ingredients: ['Ground beef or turkey (1 lb)', 'Spaghetti', 'Canned crushed tomatoes', 'Garlic', 'Oregano', 'Red wine', 'Parmesan'],
  },
  {
    id: 'chicken-parm',
    title: 'Chicken Parmesan (oven-baked)',
    type: 'weeknight',
    time: '30 min',
    tags: ['quick'],
    cuisine: 'Italian',
    notes: 'Breaded chicken breast, quick marinara, melted mozzarella. Serve over pasta or alone. Crispy not smothered.',
    ingredients: ['Chicken breast (1.5 lb)', 'Breadcrumbs', 'Eggs', 'Marinara sauce', 'Mozzarella', 'Parmesan', 'Pasta (optional)'],
  },
  {
    id: 'baked-ziti',
    title: 'Baked ziti',
    type: 'weeknight',
    time: '40 min',
    tags: ['leftovers'],
    cuisine: 'Italian',
    notes: 'Ziti tossed with marinara and ricotta, topped with mozzarella, baked until bubbly. Comfort food on autopilot.',
    ingredients: ['Ziti (1 lb)', 'Marinara sauce', 'Ricotta (15 oz)', 'Mozzarella', 'Parmesan', 'Italian sausage (optional)', 'Italian seasoning'],
  },
  {
    id: 'cacio-e-pepe',
    title: 'Cacio e pepe',
    type: 'weeknight',
    time: '15 min',
    tags: ['quick'],
    cuisine: 'Italian',
    notes: 'Three-ingredient pasta: pecorino, black pepper, pasta water emulsified into a glossy sauce. Simple Roman classic.',
    ingredients: ['Spaghetti or tonnarelli (1 lb)', 'Pecorino Romano', 'Black pepper (whole)', 'Salt'],
  },
  {
    id: 'sausage-peppers',
    title: 'Italian sausage + peppers + onions',
    type: 'weeknight',
    time: '25 min',
    tags: ['quick'],
    cuisine: 'Italian',
    notes: 'Sweet Italian sausage seared, then finished with peppers and onions. Serve on hoagies or over polenta.',
    ingredients: ['Italian sausage (1.5 lb)', 'Bell peppers', 'Yellow onion', 'Garlic', 'Hoagie rolls or polenta', 'Olive oil'],
  },

  // ── Asian ──────────────────────────────────────────────────────────────
  {
    id: 'chicken-stir-fry',
    title: 'Chicken stir-fry with rice',
    type: 'weeknight',
    time: '25 min',
    tags: ['quick'],
    cuisine: 'Asian',
    notes: 'Chicken strips, bell peppers, snap peas, light soy-ginger sauce — kept mild. Shannon skips heat, Jim adds chili oil to his bowl.',
    ingredients: ['Chicken breast (1.5 lb)', 'Bell peppers', 'Snap peas', 'Soy sauce', 'Fresh ginger', 'Garlic', 'Sesame oil', 'Jasmine rice'],
  },
  {
    id: 'beef-broccoli',
    title: 'Beef and broccoli',
    type: 'weeknight',
    time: '25 min',
    tags: ['quick'],
    cuisine: 'Asian',
    notes: 'Flank steak sliced thin against grain, fast sear, ginger-garlic-soy sauce, broccoli florets. Better than takeout in 25 min.',
    ingredients: ['Flank steak (1 lb)', 'Broccoli', 'Soy sauce', 'Oyster sauce', 'Cornstarch', 'Fresh ginger', 'Garlic', 'Jasmine rice'],
  },
  {
    id: 'teriyaki-salmon',
    title: 'Teriyaki salmon + rice + broccoli',
    type: 'weeknight',
    time: '25 min',
    tags: ['quick'],
    cuisine: 'Asian',
    notes: 'Salmon fillets glazed with quick teriyaki, broiled until caramelized. Steamed rice and broccoli on the side.',
    ingredients: ['Salmon fillets (1.5 lb)', 'Soy sauce', 'Mirin', 'Brown sugar', 'Fresh ginger', 'Garlic', 'Broccoli', 'Jasmine rice', 'Sesame seeds'],
  },
  {
    id: 'pork-fried-rice',
    title: 'Pork fried rice',
    type: 'weeknight',
    time: '20 min',
    tags: ['quick', 'leftovers'],
    cuisine: 'Asian',
    notes: 'Day-old rice is the secret. Diced pork or leftover rotisserie, eggs, peas, carrots, soy + sesame. One-pan.',
    ingredients: ['Cooked rice (chilled)', 'Pork or chicken (1 lb)', 'Eggs (3)', 'Frozen peas & carrots', 'Soy sauce', 'Sesame oil', 'Green onions'],
  },
  {
    id: 'thai-coconut-curry',
    title: 'Thai red curry chicken',
    type: 'weeknight',
    time: '30 min',
    tags: [],
    cuisine: 'Asian',
    notes: 'Red curry paste, coconut milk, chicken, bell peppers, basil. Adjust paste amount for heat tolerance. Over jasmine rice.',
    ingredients: ['Chicken thighs (1.5 lb)', 'Red curry paste', 'Coconut milk (full fat)', 'Bell peppers', 'Thai basil', 'Fish sauce', 'Brown sugar', 'Jasmine rice'],
  },

  // ── Mediterranean ──────────────────────────────────────────────────────
  {
    id: 'greek-chicken-bowls',
    title: 'Greek chicken bowls',
    type: 'weeknight',
    time: '25 min',
    tags: ['quick'],
    cuisine: 'Mediterranean',
    notes: 'Marinated chicken (lemon, oregano, garlic), rice or orzo, cucumber-tomato salad, tzatziki, feta. Bright and clean.',
    ingredients: ['Chicken breast (1.5 lb)', 'Lemon', 'Oregano', 'Garlic', 'Olive oil', 'Rice or orzo', 'Cucumber', 'Cherry tomatoes', 'Feta', 'Tzatziki'],
  },
  {
    id: 'shrimp-scampi',
    title: 'Shrimp scampi over linguine',
    type: 'weeknight',
    time: '20 min',
    tags: ['quick'],
    cuisine: 'Mediterranean',
    notes: 'Shrimp sautéed in butter, garlic, white wine, lemon, parsley. Toss with linguine. Restaurant-quality in 20 min.',
    ingredients: ['Shrimp (1 lb peeled)', 'Linguine', 'Butter', 'Garlic', 'White wine', 'Lemon', 'Fresh parsley', 'Red pepper flakes'],
  },
  {
    id: 'lemon-herb-chicken',
    title: 'Lemon-herb chicken + couscous',
    type: 'weeknight',
    time: '30 min',
    tags: [],
    cuisine: 'Mediterranean',
    notes: 'Pan-seared chicken with lemon-thyme pan sauce. Pearl couscous with herbs. Light, elegant, fast.',
    ingredients: ['Chicken breast (1.5 lb)', 'Lemon', 'Fresh thyme', 'Butter', 'Garlic', 'Pearl couscous', 'Parsley', 'Chicken broth'],
  },

  // ── Weekend dishes ─────────────────────────────────────────────────────
  {
    id: 'tri-tip-grill',
    title: 'Grilled tri-tip + garlic bread + Caesar salad',
    type: 'weekend',
    time: '60 min',
    tags: ['weekend', 'grill', 'leftovers'],
    cuisine: 'American',
    notes: 'Dry rub: salt, pepper, garlic powder. Reverse sear or direct grill. Slice thin against grain. Leftovers make great sandwiches.',
    ingredients: ['Tri-tip roast (2–3 lb)', 'French bread', 'Butter', 'Garlic', 'Romaine lettuce', 'Caesar dressing', 'Parmesan', 'Croutons'],
  },
  {
    id: 'homemade-pizza',
    title: 'Homemade pizza night',
    type: 'weekend',
    time: '45 min',
    tags: ['weekend'],
    cuisine: 'Italian',
    notes: 'Store-bought dough, good jarred sauce, fresh mozzarella. Jim does spicy sausage half, Shannon gets her preferred toppings. Oven 500°F.',
    ingredients: ['Pizza dough (store-bought)', 'Jarred marinara', 'Fresh mozzarella', 'Italian sausage (Jim)', 'Your preferred toppings', 'Olive oil', 'Fresh basil'],
  },
  {
    id: 'baby-back-ribs',
    title: 'BBQ baby back ribs + corn + coleslaw',
    type: 'weekend',
    time: '90 min',
    tags: ['weekend', 'grill'],
    cuisine: 'BBQ',
    notes: 'Low and slow in oven (275°F, 2.5 hrs) then finish on grill. Dry rub only. Classic weekend vibes.',
    ingredients: ['Baby back ribs (2 racks)', 'Dry rub spices', 'BBQ sauce (finish)', 'Corn on the cob', 'Coleslaw mix', 'Coleslaw dressing'],
  },
  {
    id: 'lasagna',
    title: 'Lasagna — make two, freeze one',
    type: 'weekend',
    time: '75 min',
    tags: ['weekend', 'leftovers'],
    cuisine: 'Italian',
    notes: 'Classic beef and ricotta. Assemble two pans, eat one, freeze one. Future-you will be grateful on a busy Wednesday.',
    ingredients: ['Ground beef (2 lb)', 'Lasagna noodles', 'Ricotta (15 oz)', 'Mozzarella (block)', 'Parmesan', 'Marinara sauce (2 jars)', 'Eggs', 'Italian seasoning'],
  },
  {
    id: 'sunday-pot-roast',
    title: 'Sunday pot roast + root vegetables',
    type: 'weekend',
    time: '3 hrs',
    tags: ['weekend', 'leftovers'],
    cuisine: 'American',
    notes: 'Chuck roast braised low in red wine and stock with carrots, potatoes, onions. Hands-off comfort.',
    ingredients: ['Chuck roast (3 lb)', 'Carrots', 'Yukon gold potatoes', 'Yellow onion', 'Red wine', 'Beef broth', 'Tomato paste', 'Fresh thyme', 'Bay leaves'],
  },
  {
    id: 'whole-roast-chicken',
    title: 'Whole roast chicken + pan vegetables',
    type: 'weekend',
    time: '90 min',
    tags: ['weekend', 'leftovers'],
    cuisine: 'American',
    notes: 'High-heat roast (425°F), butter under the skin. Vegetables roast in the drippings. Save the carcass for stock.',
    ingredients: ['Whole chicken (4–5 lb)', 'Butter', 'Lemon', 'Fresh thyme', 'Garlic', 'Yukon gold potatoes', 'Carrots', 'Yellow onion'],
  },
  {
    id: 'paella',
    title: 'Chicken & shrimp paella',
    type: 'weekend',
    time: '60 min',
    tags: ['weekend'],
    cuisine: 'Mediterranean',
    notes: 'Saffron rice with chicken thighs, shrimp, peas. Crispy socarrat on the bottom is the prize.',
    ingredients: ['Chicken thighs (1 lb)', 'Shrimp (1 lb)', 'Bomba or arborio rice', 'Saffron', 'Smoked paprika', 'Yellow onion', 'Garlic', 'Bell pepper', 'Frozen peas', 'Chicken stock', 'Lemon'],
  },
  {
    id: 'short-ribs-braised',
    title: 'Braised short ribs + mashed potatoes',
    type: 'weekend',
    time: '3.5 hrs',
    tags: ['weekend', 'leftovers'],
    cuisine: 'American',
    notes: 'Sear hard, braise in red wine and stock with mirepoix until fork-tender. Serve over buttery mash. Special-occasion energy.',
    ingredients: ['Bone-in short ribs (4 lb)', 'Carrots', 'Celery', 'Yellow onion', 'Red wine', 'Beef broth', 'Tomato paste', 'Fresh thyme', 'Yukon gold potatoes', 'Butter', 'Cream'],
  },
  {
    id: 'grilled-salmon-cedar',
    title: 'Cedar-plank grilled salmon + asparagus',
    type: 'weekend',
    time: '40 min',
    tags: ['weekend', 'grill'],
    cuisine: 'American',
    notes: 'Soak cedar plank 1 hr, salmon on plank over indirect heat. Smoky and gorgeous. Asparagus on the grill alongside.',
    ingredients: ['Salmon side (2 lb)', 'Cedar plank', 'Lemon', 'Brown sugar', 'Dijon mustard', 'Asparagus', 'Olive oil'],
  },
]

// Day labels for plan generation
export const WEEKDAYS = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday']
export const WEEKEND_DAYS = ['Saturday', 'Sunday']

export const TAG_COLORS = {
  quick: { bg: '#E4EDE5', color: '#3D6B42' },
  leftovers: { bg: '#F7F0DC', color: '#8B6914' },
  grill: { bg: '#F5E8DC', color: '#8B3E1A' },
  weekend: { bg: '#E8E4F5', color: '#5A3D8B' },
}

export const CUISINE_ICONS = {
  Italian: '🍝',
  Mexican: '🌮',
  American: '🍔',
  Asian: '🥢',
  BBQ: '🔥',
  Mediterranean: '🫒',
}
