export const INITIAL_PLAN = {
  week1: [
    {
      id: 'w1-mon',
      day: 'Monday',
      week: 1,
      type: 'weeknight',
      title: 'Sheet-pan chicken thighs + roasted potatoes',
      time: '25 min',
      tags: ['quick', 'leftovers'],
      cuisine: 'American',
      notes: 'Season with garlic, olive oil, paprika. Everything on one pan at 425°F. Make extra — Friday quesadillas sorted.',
      ingredients: ['Chicken thighs (2 lb)', 'Yukon gold potatoes', 'Garlic', 'Olive oil', 'Paprika', 'Salt & pepper'],
      cooked: false,
      rating: 0,
      shannonsNotes: '',
      jimsNotes: '',
    },
    {
      id: 'w1-tue',
      day: 'Tuesday',
      week: 1,
      type: 'weeknight',
      title: 'Ground beef tacos',
      time: '20 min',
      tags: ['quick'],
      cuisine: 'Mexican',
      notes: 'Quick seasoned beef, warm tortillas, shredded cheese, pico, sour cream, avocado. Shannon mild, Jim adds heat to his bowl.',
      ingredients: ['Ground beef (1 lb)', 'Flour tortillas', 'Shredded Mexican cheese', 'Sour cream', 'Avocado', 'Roma tomatoes', 'Limes', 'Taco seasoning'],
      cooked: false,
      rating: 0,
      shannonsNotes: '',
      jimsNotes: '',
    },
    {
      id: 'w1-wed',
      day: 'Wednesday',
      week: 1,
      type: 'weeknight',
      title: 'Pasta with quick meat sauce',
      time: '25 min',
      tags: ['quick', 'leftovers'],
      cuisine: 'Italian',
      notes: 'Ground beef or turkey, crushed tomatoes elevated with garlic, oregano, splash of red wine. Parmesan at the table. Make a big batch.',
      ingredients: ['Ground beef or turkey (1 lb)', 'Spaghetti', 'Canned crushed tomatoes', 'Garlic', 'Oregano', 'Red wine', 'Parmesan'],
      cooked: false,
      rating: 0,
      shannonsNotes: '',
      jimsNotes: '',
    },
    {
      id: 'w1-thu',
      day: 'Thursday',
      week: 1,
      type: 'weeknight',
      title: 'Smash burgers + oven fries',
      time: '20 min',
      tags: ['quick'],
      cuisine: 'American',
      notes: '80/20 beef smashed thin in cast iron, American or cheddar melted on. Oven fries at 425°F.',
      ingredients: ['80/20 ground beef (1 lb)', 'Burger buns', 'American or cheddar cheese', 'Russet potatoes', 'Ketchup', 'Mustard', 'Lettuce, tomato, onion'],
      cooked: false,
      rating: 0,
      shannonsNotes: '',
      jimsNotes: '',
    },
    {
      id: 'w1-fri',
      day: 'Friday',
      week: 1,
      type: 'weeknight',
      title: 'Chicken quesadillas',
      time: '15 min',
      tags: ['quick', 'leftovers'],
      cuisine: 'Mexican',
      notes: 'Use leftover chicken from Monday or rotisserie. Flour tortillas, shredded cheese, quick pan crisp. Store-bought salsa.',
      ingredients: ['Leftover chicken or rotisserie', 'Flour tortillas', 'Shredded cheese', 'Sour cream', 'Salsa'],
      cooked: false,
      rating: 0,
      shannonsNotes: '',
      jimsNotes: '',
    },
    {
      id: 'w1-sat',
      day: 'Saturday',
      week: 1,
      type: 'weekend',
      title: 'Grilled tri-tip + garlic bread + Caesar salad',
      time: '60 min',
      tags: ['weekend', 'grill', 'leftovers'],
      cuisine: 'American',
      notes: 'Dry rub: salt, pepper, garlic powder. Reverse sear or direct grill. Slice thin against grain. Leftovers make great sandwiches Sunday.',
      ingredients: ['Tri-tip roast (2–3 lb)', 'French bread', 'Butter', 'Garlic', 'Romaine lettuce', 'Caesar dressing', 'Parmesan', 'Croutons'],
      cooked: false,
      rating: 0,
      shannonsNotes: '',
      jimsNotes: '',
    },
    {
      id: 'w1-sun',
      day: 'Sunday',
      week: 1,
      type: 'weekend',
      title: 'Homemade pizza night',
      time: '45 min',
      tags: ['weekend'],
      cuisine: 'Italian',
      notes: 'Store-bought dough, good jarred sauce, fresh mozzarella. Jim does spicy sausage half, Shannon gets her preferred toppings. Oven 500°F.',
      ingredients: ['Pizza dough (store-bought)', 'Jarred marinara', 'Fresh mozzarella', 'Italian sausage (Jim)', 'Your preferred toppings', 'Olive oil', 'Fresh basil'],
      cooked: false,
      rating: 0,
      shannonsNotes: '',
      jimsNotes: '',
    },
  ],
  week2: [
    {
      id: 'w2-mon',
      day: 'Monday',
      week: 2,
      type: 'weeknight',
      title: 'Chicken stir-fry with rice',
      time: '25 min',
      tags: ['quick'],
      cuisine: 'Asian',
      notes: 'Chicken strips, bell peppers, snap peas, light soy-ginger sauce — kept mild. Shannon skips heat, Jim adds chili oil to his bowl.',
      ingredients: ['Chicken breast (1.5 lb)', 'Bell peppers', 'Snap peas', 'Soy sauce', 'Fresh ginger', 'Garlic', 'Sesame oil', 'Jasmine rice'],
      cooked: false,
      rating: 0,
      shannonsNotes: '',
      jimsNotes: '',
    },
    {
      id: 'w2-tue',
      day: 'Tuesday',
      week: 2,
      type: 'weeknight',
      title: 'Taco bowls (deconstructed)',
      time: '20 min',
      tags: ['quick'],
      cuisine: 'Mexican',
      notes: 'Rice base, seasoned meat, black beans, corn, shredded cheese, sour cream. Easy to customize by bowl.',
      ingredients: ['Ground turkey or beef (1 lb)', 'Rice', 'Canned black beans', 'Corn', 'Shredded cheese', 'Sour cream', 'Taco seasoning', 'Lime'],
      cooked: false,
      rating: 0,
      shannonsNotes: '',
      jimsNotes: '',
    },
    {
      id: 'w2-wed',
      day: 'Wednesday',
      week: 2,
      type: 'weeknight',
      title: 'Chicken Parmesan (oven-baked)',
      time: '30 min',
      tags: ['quick'],
      cuisine: 'Italian',
      notes: 'Breaded chicken breast, quick marinara, melted mozzarella. Serve over pasta or alone. Crispy not smothered.',
      ingredients: ['Chicken breast (1.5 lb)', 'Breadcrumbs', 'Eggs', 'Marinara sauce', 'Mozzarella', 'Parmesan', 'Pasta (optional)'],
      cooked: false,
      rating: 0,
      shannonsNotes: '',
      jimsNotes: '',
    },
    {
      id: 'w2-thu',
      day: 'Thursday',
      week: 2,
      type: 'weeknight',
      title: 'Steak tacos with chimichurri',
      time: '20 min',
      tags: ['quick', 'grill'],
      cuisine: 'Mexican',
      notes: 'Skirt or flank steak, quick high-heat sear, slice thin. Chimichurri is bright not heavy. Not spicy by default.',
      ingredients: ['Skirt or flank steak (1.5 lb)', 'Corn tortillas', 'Fresh parsley', 'Garlic', 'Red wine vinegar', 'Olive oil', 'White onion', 'Cilantro'],
      cooked: false,
      rating: 0,
      shannonsNotes: '',
      jimsNotes: '',
    },
    {
      id: 'w2-fri',
      day: 'Friday',
      week: 2,
      type: 'weeknight',
      title: 'BBQ chicken wraps + chips',
      time: '15 min',
      tags: ['quick', 'leftovers'],
      cuisine: 'American',
      notes: 'Rotisserie chicken + BBQ sauce, flour tortillas, coleslaw, cheddar. Five-minute assembly. Low-effort Friday.',
      ingredients: ['Rotisserie chicken', 'BBQ sauce', 'Flour tortillas', 'Coleslaw mix', 'Cheddar cheese', 'Tortilla chips'],
      cooked: false,
      rating: 0,
      shannonsNotes: '',
      jimsNotes: '',
    },
    {
      id: 'w2-sat',
      day: 'Saturday',
      week: 2,
      type: 'weekend',
      title: 'BBQ baby back ribs + corn + coleslaw',
      time: '90 min',
      tags: ['weekend', 'grill'],
      cuisine: 'BBQ',
      notes: 'Low and slow in oven (275°F, 2.5 hrs) then finish on grill. Dry rub only. Classic weekend vibes.',
      ingredients: ['Baby back ribs (2 racks)', 'Dry rub spices', 'BBQ sauce (finish)', 'Corn on the cob', 'Coleslaw mix', 'Coleslaw dressing'],
      cooked: false,
      rating: 0,
      shannonsNotes: '',
      jimsNotes: '',
    },
    {
      id: 'w2-sun',
      day: 'Sunday',
      week: 2,
      type: 'weekend',
      title: 'Lasagna — make two, freeze one',
      time: '75 min',
      tags: ['weekend', 'leftovers'],
      cuisine: 'Italian',
      notes: 'Classic beef and ricotta. Assemble two pans, eat one, freeze one. Future-you will be grateful on a busy Wednesday.',
      ingredients: ['Ground beef (2 lb)', 'Lasagna noodles', 'Ricotta (15 oz)', 'Mozzarella (block)', 'Parmesan', 'Marinara sauce (2 jars)', 'Eggs', 'Italian seasoning'],
      cooked: false,
      rating: 0,
      shannonsNotes: '',
      jimsNotes: '',
    },
  ]
}

export const TAG_COLORS = {
  quick: { bg: '#E4EDE5', color: '#3D6B42' },
  leftovers: { bg: '#F7F0DC', color: '#8B6914' },
  grill: { bg: '#F5E8DC', color: '#8B3E1A' },
  weekend: { bg: '#E8E4F5', color: '#5A3D8B' },
}

export const CUISINE_ICONS = {
  Italian: '🍝',
  Mexican: '🌮',
  American: '🍔',
  Asian: '🥢',
  BBQ: '🔥',
}
